# Generated by Django 4.2.16 on 2024-11-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Otp_A', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
    ]
