# Generated by Django 4.2.16 on 2024-11-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Otp_A', '0003_remove_user_phone_number_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
